version: "3.1"
services:
  proxy:
    image: nginx:1.15-alpine
    ports:
      - "8080:80"
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf/domain.conf:/etc/nginx/domain.conf:ro


  # ========================================
  # Falls Sie das Person-SCS implementieren
  # ergänzen Sie diesen Teil
  person:

  persondb:

  # ========================================
  # Falls Sie das Projekt-SCS implementieren
  # ergänzen Sie diesen Teil
  projekt:

  projektdb:

  # ========================================
